model_list:
  - model_name: gemini-flash-lite         # alias your app uses
    litellm_params:
      model: gemini/gemini-2.5-flash-lite
      api_key: AIzaSyAQRJPlS_o9sQcdlP_op6jI9AqlN6bq3CE
    rpm: 15         # allow up to 120 requests per minute

router_settings:
  enable_pre_call_checks: true
  num_retries: 3